// Generated via https://supabase.com/docs/guides/api/generating-types#generating-types-using-supabase-cli
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
	public: {
		Tables: {
			'donations-all': {
				Row: {
					donation_id: string | null;
					donor: string | null;
					donee: string | null;
					amount: string | null;
					amount_original_currency: string | null;
					original_currency: string | null;
					currency_conversion_date: string | null;
					currency_conversion_basis: string | null;
					fraction: string | null;
					donation_date: string | null;
					donation_date_precision: string | null;
					donation_date_basis: string | null;
					cause_area: string | null;
					url: string | null;
					donor_cause_area_url: string | null;
					notes: string | null;
					donation_process: string | null;
					intended_use_of_funds_category: string | null;
					intended_use_of_funds: string | null;
					intended_funding_timeframe_in_months: string | null;
					donor_donee_reason: string | null;
					donor_amount_reason: string | null;
					donor_timing_reason: string | null;
					donor_next_donation_thoughts: string | null;
					donor_retrospective: string | null;
					payment_modality: string | null;
					match_eligible: string | null;
					goal_amount: string | null;
					influencer: string | null;
					employer_match: string | null;
					matching_employer: string | null;
					special_donation_reason: string | null;
					donation_earmark: string | null;
					affected_countries: string | null;
					affected_states: string | null;
					affected_cities: string | null;
					affected_regions: string | null;
					donation_announcement_date: string | null;
					donation_announcement_date_precision: string | null;
					donation_announcement_url: string | null;
					predictions: string | null;
					is_contractwork: string | null;
				};
				Insert: {
					donation_id?: string | null;
					donor?: string | null;
					donee?: string | null;
					amount?: string | null;
					amount_original_currency?: string | null;
					original_currency?: string | null;
					currency_conversion_date?: string | null;
					currency_conversion_basis?: string | null;
					fraction?: string | null;
					donation_date?: string | null;
					donation_date_precision?: string | null;
					donation_date_basis?: string | null;
					cause_area?: string | null;
					url?: string | null;
					donor_cause_area_url?: string | null;
					notes?: string | null;
					donation_process?: string | null;
					intended_use_of_funds_category?: string | null;
					intended_use_of_funds?: string | null;
					intended_funding_timeframe_in_months?: string | null;
					donor_donee_reason?: string | null;
					donor_amount_reason?: string | null;
					donor_timing_reason?: string | null;
					donor_next_donation_thoughts?: string | null;
					donor_retrospective?: string | null;
					payment_modality?: string | null;
					match_eligible?: string | null;
					goal_amount?: string | null;
					influencer?: string | null;
					employer_match?: string | null;
					matching_employer?: string | null;
					special_donation_reason?: string | null;
					donation_earmark?: string | null;
					affected_countries?: string | null;
					affected_states?: string | null;
					affected_cities?: string | null;
					affected_regions?: string | null;
					donation_announcement_date?: string | null;
					donation_announcement_date_precision?: string | null;
					donation_announcement_url?: string | null;
					predictions?: string | null;
					is_contractwork?: string | null;
				};
				Update: {
					donation_id?: string | null;
					donor?: string | null;
					donee?: string | null;
					amount?: string | null;
					amount_original_currency?: string | null;
					original_currency?: string | null;
					currency_conversion_date?: string | null;
					currency_conversion_basis?: string | null;
					fraction?: string | null;
					donation_date?: string | null;
					donation_date_precision?: string | null;
					donation_date_basis?: string | null;
					cause_area?: string | null;
					url?: string | null;
					donor_cause_area_url?: string | null;
					notes?: string | null;
					donation_process?: string | null;
					intended_use_of_funds_category?: string | null;
					intended_use_of_funds?: string | null;
					intended_funding_timeframe_in_months?: string | null;
					donor_donee_reason?: string | null;
					donor_amount_reason?: string | null;
					donor_timing_reason?: string | null;
					donor_next_donation_thoughts?: string | null;
					donor_retrospective?: string | null;
					payment_modality?: string | null;
					match_eligible?: string | null;
					goal_amount?: string | null;
					influencer?: string | null;
					employer_match?: string | null;
					matching_employer?: string | null;
					special_donation_reason?: string | null;
					donation_earmark?: string | null;
					affected_countries?: string | null;
					affected_states?: string | null;
					affected_cities?: string | null;
					affected_regions?: string | null;
					donation_announcement_date?: string | null;
					donation_announcement_date_precision?: string | null;
					donation_announcement_url?: string | null;
					predictions?: string | null;
					is_contractwork?: string | null;
				};
			};
			donations20: {
				Row: {
					donation_id: number;
					donor: string | null;
					donee: string | null;
					amount: number | null;
					amount_original_currency: string | null;
					original_currency: string | null;
					currency_conversion_date: string | null;
					currency_conversion_basis: string | null;
					fraction: string | null;
					donation_date: string | null;
					donation_date_precision: string | null;
					donation_date_basis: string | null;
					cause_area: string | null;
					url: string | null;
					donor_cause_area_url: string | null;
					notes: string | null;
					donation_process: string | null;
					intended_use_of_funds_category: string | null;
					intended_use_of_funds: string | null;
					intended_funding_timeframe_in_months: string | null;
					donor_donee_reason: string | null;
					donor_amount_reason: string | null;
					donor_timing_reason: string | null;
					donor_next_donation_thoughts: string | null;
					donor_retrospective: string | null;
					payment_modality: string | null;
					match_eligible: string | null;
					goal_amount: string | null;
					influencer: string | null;
					employer_match: string | null;
					matching_employer: string | null;
					special_donation_reason: string | null;
					donation_earmark: string | null;
					affected_countries: string | null;
					affected_states: string | null;
					affected_cities: string | null;
					affected_regions: string | null;
					donation_announcement_date: string | null;
					donation_announcement_date_precision: string | null;
					donation_announcement_url: string | null;
					predictions: string | null;
					is_contractwork: string | null;
				};
				Insert: {
					donation_id: number;
					donor?: string | null;
					donee?: string | null;
					amount?: number | null;
					amount_original_currency?: string | null;
					original_currency?: string | null;
					currency_conversion_date?: string | null;
					currency_conversion_basis?: string | null;
					fraction?: string | null;
					donation_date?: string | null;
					donation_date_precision?: string | null;
					donation_date_basis?: string | null;
					cause_area?: string | null;
					url?: string | null;
					donor_cause_area_url?: string | null;
					notes?: string | null;
					donation_process?: string | null;
					intended_use_of_funds_category?: string | null;
					intended_use_of_funds?: string | null;
					intended_funding_timeframe_in_months?: string | null;
					donor_donee_reason?: string | null;
					donor_amount_reason?: string | null;
					donor_timing_reason?: string | null;
					donor_next_donation_thoughts?: string | null;
					donor_retrospective?: string | null;
					payment_modality?: string | null;
					match_eligible?: string | null;
					goal_amount?: string | null;
					influencer?: string | null;
					employer_match?: string | null;
					matching_employer?: string | null;
					special_donation_reason?: string | null;
					donation_earmark?: string | null;
					affected_countries?: string | null;
					affected_states?: string | null;
					affected_cities?: string | null;
					affected_regions?: string | null;
					donation_announcement_date?: string | null;
					donation_announcement_date_precision?: string | null;
					donation_announcement_url?: string | null;
					predictions?: string | null;
					is_contractwork?: string | null;
				};
				Update: {
					donation_id?: number;
					donor?: string | null;
					donee?: string | null;
					amount?: number | null;
					amount_original_currency?: string | null;
					original_currency?: string | null;
					currency_conversion_date?: string | null;
					currency_conversion_basis?: string | null;
					fraction?: string | null;
					donation_date?: string | null;
					donation_date_precision?: string | null;
					donation_date_basis?: string | null;
					cause_area?: string | null;
					url?: string | null;
					donor_cause_area_url?: string | null;
					notes?: string | null;
					donation_process?: string | null;
					intended_use_of_funds_category?: string | null;
					intended_use_of_funds?: string | null;
					intended_funding_timeframe_in_months?: string | null;
					donor_donee_reason?: string | null;
					donor_amount_reason?: string | null;
					donor_timing_reason?: string | null;
					donor_next_donation_thoughts?: string | null;
					donor_retrospective?: string | null;
					payment_modality?: string | null;
					match_eligible?: string | null;
					goal_amount?: string | null;
					influencer?: string | null;
					employer_match?: string | null;
					matching_employer?: string | null;
					special_donation_reason?: string | null;
					donation_earmark?: string | null;
					affected_countries?: string | null;
					affected_states?: string | null;
					affected_cities?: string | null;
					affected_regions?: string | null;
					donation_announcement_date?: string | null;
					donation_announcement_date_precision?: string | null;
					donation_announcement_url?: string | null;
					predictions?: string | null;
					is_contractwork?: string | null;
				};
			};
			donationsea: {
				Row: {
					donation_id: number;
					donor: string | null;
					donee: string | null;
					amount: string | null;
					amount_original_currency: string | null;
					original_currency: string | null;
					currency_conversion_date: string | null;
					currency_conversion_basis: string | null;
					fraction: string | null;
					donation_date: string | null;
					donation_date_precision: string | null;
					donation_date_basis: string | null;
					cause_area: string | null;
					url: string | null;
					donor_cause_area_url: string | null;
					notes: string | null;
					donation_process: string | null;
					intended_use_of_funds_category: string | null;
					intended_use_of_funds: string | null;
					intended_funding_timeframe_in_months: string | null;
					donor_donee_reason: string | null;
					donor_amount_reason: string | null;
					donor_timing_reason: string | null;
					donor_next_donation_thoughts: string | null;
					donor_retrospective: string | null;
					payment_modality: string | null;
					match_eligible: string | null;
					goal_amount: string | null;
					influencer: string | null;
					employer_match: string | null;
					matching_employer: string | null;
					special_donation_reason: string | null;
					donation_earmark: string | null;
					affected_countries: string | null;
					affected_states: string | null;
					affected_cities: string | null;
					affected_regions: string | null;
					donation_announcement_date: string | null;
					donation_announcement_date_precision: string | null;
					donation_announcement_url: string | null;
					predictions: string | null;
					is_contractwork: string | null;
				};
				Insert: {
					donation_id: number;
					donor?: string | null;
					donee?: string | null;
					amount?: string | null;
					amount_original_currency?: string | null;
					original_currency?: string | null;
					currency_conversion_date?: string | null;
					currency_conversion_basis?: string | null;
					fraction?: string | null;
					donation_date?: string | null;
					donation_date_precision?: string | null;
					donation_date_basis?: string | null;
					cause_area?: string | null;
					url?: string | null;
					donor_cause_area_url?: string | null;
					notes?: string | null;
					donation_process?: string | null;
					intended_use_of_funds_category?: string | null;
					intended_use_of_funds?: string | null;
					intended_funding_timeframe_in_months?: string | null;
					donor_donee_reason?: string | null;
					donor_amount_reason?: string | null;
					donor_timing_reason?: string | null;
					donor_next_donation_thoughts?: string | null;
					donor_retrospective?: string | null;
					payment_modality?: string | null;
					match_eligible?: string | null;
					goal_amount?: string | null;
					influencer?: string | null;
					employer_match?: string | null;
					matching_employer?: string | null;
					special_donation_reason?: string | null;
					donation_earmark?: string | null;
					affected_countries?: string | null;
					affected_states?: string | null;
					affected_cities?: string | null;
					affected_regions?: string | null;
					donation_announcement_date?: string | null;
					donation_announcement_date_precision?: string | null;
					donation_announcement_url?: string | null;
					predictions?: string | null;
					is_contractwork?: string | null;
				};
				Update: {
					donation_id?: number;
					donor?: string | null;
					donee?: string | null;
					amount?: string | null;
					amount_original_currency?: string | null;
					original_currency?: string | null;
					currency_conversion_date?: string | null;
					currency_conversion_basis?: string | null;
					fraction?: string | null;
					donation_date?: string | null;
					donation_date_precision?: string | null;
					donation_date_basis?: string | null;
					cause_area?: string | null;
					url?: string | null;
					donor_cause_area_url?: string | null;
					notes?: string | null;
					donation_process?: string | null;
					intended_use_of_funds_category?: string | null;
					intended_use_of_funds?: string | null;
					intended_funding_timeframe_in_months?: string | null;
					donor_donee_reason?: string | null;
					donor_amount_reason?: string | null;
					donor_timing_reason?: string | null;
					donor_next_donation_thoughts?: string | null;
					donor_retrospective?: string | null;
					payment_modality?: string | null;
					match_eligible?: string | null;
					goal_amount?: string | null;
					influencer?: string | null;
					employer_match?: string | null;
					matching_employer?: string | null;
					special_donation_reason?: string | null;
					donation_earmark?: string | null;
					affected_countries?: string | null;
					affected_states?: string | null;
					affected_cities?: string | null;
					affected_regions?: string | null;
					donation_announcement_date?: string | null;
					donation_announcement_date_precision?: string | null;
					donation_announcement_url?: string | null;
					predictions?: string | null;
					is_contractwork?: string | null;
				};
			};
			donationz: {
				Row: {
					donation_id: number;
					donor: string | null;
					donee: string | null;
					amount: number | null;
				};
				Insert: {
					donation_id: number;
					donor?: string | null;
					donee?: string | null;
					amount?: number | null;
				};
				Update: {
					donation_id?: number;
					donor?: string | null;
					donee?: string | null;
					amount?: number | null;
				};
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			[_ in never]: never;
		};
	};
}
